config/routes.rb
Rails.application.routes.draw do

  resources :brands , only: [:index , :edit, :update ,:new ,:create , :destroy]
  resources :subcategories, only: [:new ,:index,:edit,:update,:create , :destroy]
  resources :admin , only: [:index , :edit ,:update]
  resources :categories , only: [:new,:create,:edit,:update,:destroy]
  resources :users
  resources :items
  resources :carts
  root 'items#index'

  resources :sessions , only: [:new , :create , :destroy]
  get "/login" => "sessions#new" , as: "login"
  delete "/logout" => "sessions#destroy" , as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/edit.html.erb
 <h4> <%= link_to "Admin Dashboard" , admin_index_path, method: "get" , class: "btn btn-success" %>
 <br>
 <br>
<%= form_for(current_user , url: admin_path(current_user[:id]) , method: "put") do |f|  %>
	<div class="field form-group row">
		<%= label_tag :old_password , nil , class: "col-sm-2 col-sm-label" %>
		<div class="col-sm-4">
			<%= password_field_tag :oldpassword , nil ,class: "form-control" %>
		</div>
	</div>
	<div class="field form-group row" >
		<%= f.label :New_password , class: "col-sm-2 col-sm-label" %>
		<div class="col-sm-4">
			<%= f.password_field :password , class: "form-control" %>
		</div>
	</div>
	<div class="action" >
		<%= f.submit "Change" , class: "btn btn-success" %>
	</div>
<% end %>

app/views/admin/index.html.erb
<h1>Admin Dashboard</h1>
<h2><%= notice %></h2>

<ul class="nav justify-content-center nav-tabs">
  <li class="nav-item">
    <%= link_to "Add new category" , new_category_path , class: "nav-link" %>
  </li>
  <li class="nav-item">
    <%= link_to "All Users" , users_path , class: "nav-link"  %>
  </li>
  <li class="nav-item">
    <%= link_to "Add new items to sell" , new_item_path, method: "get" , class: "nav-link" %>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Add Subcategory <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
      	<%= form_for(:category, url: new_subcategory_path, method: "get") do |f| %>
					<%= f.label :category %>
					<%= f.select(:id,options_from_collection_for_select( Category.all , :id , :name) , { prompt: "Select Category" }) %>
					<%= f.submit "Go" , class: "btn btn-success" %>
				<% end %>
      </li>
    </ul>
  </li>
  <li role="presentation" class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
      Add Brand <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li>
      	<%= form_tag new_brand_path , method: "get" do %>
					<%= select_tag(:category , options_from_collection_for_select( Category.all , :id , :name) , { prompt: "Select Category" , class: "auto-update"} ) %>
					<br><br>
					<%= select_tag(:subcategory , "" , {prompt: "Select subcategory", class: "sub-update"} ) %>
					<br><br>
					<%= submit_tag("GO", class: "btn btn-success") %>
				<% end %>
      </li>
    </ul>
  </li>
  <li  class="nav-item">
    <%= link_to "Change Password" , edit_admin_path(current_user.id) , method: "get" %>
  </li>
</ul>


<h3> Recent Transactions</h3>

<% @allOrders.each do |order| %>
<% total=0 %>
		<div class="alert alert-warning row" role="alert">
			<div class="col-sm-2">
				Order id:	<%= order.id %>
			</div>
			<div class="col-sm-2">
				User id: <%= order.user.id %>
			</div>
			<div class="col-sm-2">
				User name: <%= order.user.name %>
			</div>
			<div class="col-sm-4">
				Delivery Address: <%= order.daddress %>
				<p> Payment Type: COD(Cash on Delivery) </p>
			</div>
			<div class="col-sm-2">
				Date and Time : <%= order.created_at.in_time_zone("Kolkata").strftime(" %d %m %Y , %I %M %p %Z") %>
			</div>
		</div>
		<table class="table">
	  	<thead>
	    	<tr>
	      	<th>#</th>
	      	<th>Title</th>
	      	<th>Price</th>
	      	<th>Quantity</th>
	      	<th>Description</th>
	      	<th>Option </th> 
	    	</tr>
	  	</thead>
	  	<tbody>
	  	<% orderitem = order.OrderedItems %>
	  	<% orderitem.each do |oi| %>
	    	<tr>
	      	<th scope="row"><%= oi.id %></th>
	      	<td><%= oi.title %></td>
	      	<td><%= oi.price %></td>
	      	<td><%= oi.quantity %> </td>
	      	<td><%= oi.description %></td>
	      	<td><%= link_to "View" , oi.item %> </td>
	    	</tr>
	    	<% floatPrice = oi[:price].to_f %>
        <% total= total+ (floatPrice*oi[:quantity]) %>
	    <% end %>
	  	</tbody>
		</table>
		<h4 class="pull-right"> Grand Total = <%= total %> </h4>
		<p class="clearfix"> </p>
<% end %>