config/routes.rb
Rails.application.routes.draw do

  resources :brands , only: [:index , :edit, :update ,:new ,:create , :destroy]
  resources :subcategories, only: [:new ,:index,:edit,:update,:create , :destroy]
  resources :admin , only: [:index , :edit ,:update]
  resources :categories , only: [:new,:create,:edit,:update,:destroy]
  resources :users
  resources :items
  resources :carts
  root 'items#index'

  resources :sessions , only: [:new , :create , :destroy]
  get "/login" => "sessions#new" , as: "login"
  delete "/logout" => "sessions#destroy" , as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user , optional: true
  belongs_to :item , optional: true

  scope :quantity , -> (id_item, id_user){ where("item_id=? and user_id=?","#{id_item}","#{id_user}").count }
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  skip_before_action :ensure_admin

  def index
  end

  def create
  	@itemNumber = params[:format]
  	@cartItem = Cart.new
  	@cartItem.save
  	@theItem = Item.find_by(id: @itemNumber)
  	@theItem.carts << @cartItem
  	current_user.carts << @cartItem
  	redirect_to carts_path , notice: "Item successfully added"
  end

  def update
  	itemsInCartOfUser = Cart.where(user_id: current_user.id)
  	itemToDelete = itemsInCartOfUser.find_by(item_id: params[:id])
  	itemToDelete.destroy
  	redirect_to carts_path , notice: "A item was removed"
  end

  def edit
    cart = Cart.where(user_id: current_user.id)
    itemsToDelete = cart.where(item_id: params[:id])
    itemsToDelete.each do |t|
      t.destroy
    end
    redirect_to carts_path , notice: "Item removed successfully"
  end

  def destroy
  	itemsToBuy = current_user.my_cart_items
    if itemsToBuy==[]
      redirect_to carts_path
    else
    	itemIds = itemsToBuy.pluck :id
    	current_user.items << itemsToBuy
      address = params[:daddress]
      if params[:daddress]==""
        address= current_user.address
      end
      current_order = current_user.orders.create(daddress: address)
      itemsToBuy.each do |item|
        current_item = current_order.OrderedItems.create(title: item.title , price: item.price , description: item.description, quantity: Cart.quantity(item.id,current_user.id))
        current_item.save!
        item.OrderedItems << current_item
      end
      current_user.carts.destroy_all
    	redirect_to user_path(current_user.id) , notice: "Your Order with id #{current_order.id} was placed successfully"
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/index.html.erb
<%= notice %>
<h1>Your Cart</h1>
<%= link_to "Keep on Shopping" , root_path , class: "btn btn-success pull-right" %>
<% cartItems = current_user.my_cart_items %>
<table class="table">
	<thead>
  	<tr>
    	<th>Id</th>
    	<th>Title</th>
    	<th>Price</th>
      <th>Quantity</th>
    	<th>Options</th>
  	</tr>
	</thead>
	<tbody>
  <% total = 0 %>
	<% cartItems.each do |theItem| %>
  <% quantity = Cart.quantity(theItem[:id], current_user.id) %>
  	<tr>
    	<th scope="row"><%= theItem[:id] %></th>
    	<td><%= theItem[:title] %></td>
    	<td><%= theItem[:price] %></td>
      <td><%= link_to "" , carts_path(theItem.id) , method: :post , class: "glyphicon glyphicon-triangle-top" %> <%= quantity %> <%= link_to "" , cart_path(theItem) , method: :put , class: "glyphicon glyphicon-triangle-bottom" %> </td>
    	<td><%= link_to  "Delete" , edit_cart_path(theItem.id) %> </td>
  	</tr>
    <% floatPrice = theItem[:price].to_f %>
    <% total = total + (floatPrice*quantity) %>
  <% end %>
  </tbody>
</table>
<h4 class="pull-right">Total = <%= total %> </h4> 
<p class="clearfix" > </p> 
<div class=buttons>
<% unless current_user.carts.first.nil? %>
  <%= form_tag current_user.carts.first , method: :delete do %>
    <%= submit_tag "Buy and Checkout" , class: "btn btn-success pull-right" %>
    <div class="form-group row">
      <%= label_tag :Delivery_Address , nil ,class: "col-sm-12 col-sm-label" %>
      <div class="col-sm-6">
        <%= text_area_tag :daddress , current_user.address , class: "form-control"%>
      </div>
    </div>
  <% end %>
  <p>Payment Type:COD</p>
  <small>* if delivery address is left empty then items will be delivered to the address used while signing up. </small>
<% end %>
</div>