config/routes.rb
Rails.application.routes.draw do

  resources :brands , only: [:index , :edit, :update ,:new ,:create , :destroy]
  resources :subcategories, only: [:new ,:index,:edit,:update,:create , :destroy]
  resources :admin , only: [:index , :edit ,:update]
  resources :categories , only: [:new,:create,:edit,:update,:destroy]
  resources :users
  resources :items
  resources :carts
  root 'items#index'

  resources :sessions , only: [:new , :create , :destroy]
  get "/login" => "sessions#new" , as: "login"
  delete "/logout" => "sessions#destroy" , as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord

  has_attached_file :avatar, styles: { medium: "300x300>" , thumb: "140x100#" }, default_url: "http://via.placeholder.com/140x100"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/	
  validates :title , :price , presence: true
  validates :price , numericality: { message: "Integer Only"}
  belongs_to :brand, optional: true
  has_and_belongs_to_many :users
  has_many :carts , dependent: :destroy
  has_many :OrderedItems , dependent: :nullify



  def getbrand
   	Brand.find_by(id: self[:brand_id]) unless self[:brand_id].nil?
  end

  def getsubcategory
  	Subcategory.find_by(id: getbrand[:subcategory_id]) unless getbrand.nil?
  end

  def getcategory
  	Category.find_by(id: getsubcategory[:category_id]) unless getsubcategory.nil?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_post , only: [:show , :edit , :update , :destroy]
  skip_before_action :ensure_login , only: [:index , :show]
  skip_before_action :ensure_admin , only: [:index, :show]
  
  def index
  	@test = params[:category]
  	@test2 = params[:subcategory]
  	@test3 = params[:brand]
  	@all_items = Item.all.order(id: :desc) if @test.nil?  || @test==""
    
    unless @test.nil? || @test==""
    	@cat = Category.find(@test) 
    	@all_items = @cat.items 
    end

  	@subcat = @cat.subcategories.find_by(id: @test2) unless @test2.nil? || @test2=="" 	
  	@all_items = @subcat.items unless @subcat == nil

  	@brand = @subcat.brands.find_by(id: @test3) unless @test3.nil? || @test3=="" || @subcat == nil
  	@all_items = @brand.items unless @brand == nil

    @userName = User.find_by(id: session[:user_id])
    

  	respond_to do |format|
  		format.html
  		format.json
  		format.js 
  	end
  end

  def new
  end
  
  def create
    @title = params[:title]
    @price = params[:price]
    @desc = params[:description]
    @av = params[:avatar]
    if @title=="" || @price=="" || @desc==""  || params[:category]=="" || params[:subcategory]=="" || params[:brand]==""
      redirect_to new_item_path , alert: "fields cannot be empty"
    else
      @category = Category.find_by(id: params[:category])
      @subcat = @category.subcategories.find_by(id: params[:subcategory])
      @brand = @subcat.brands.find_by(id: params[:brand])
      @newItem =  @brand.items.create title: @title , price: @price , description: @desc , avatar: @av
      if @newItem.save 
        redirect_to admin_index_path , notice: "Success for new item"
      else
        redirect_to new_item_path , notice: "Item was not added. Price must be a number"
      end    
    end

  end

  def show
    @userName = User.find_by(id: session[:user_id])
  end

  def edit
  end

  def update
    unless params[:category]=="" || params[:subcategory]=="" || params[:brand]==""
      @cat = Category.find_by(id: params[:category])
      @subcat = Subcategory.find_by(id: params[:subcategory])
      @newBrand = Brand.find_by(id: params[:brand])

      item_name = params[:item][:title]
      item_price = params[:item][:price]
      item_description = params[:item][:description]

      @item = Item.find_by(id: params[:id])
      @av = params[:item][:avatar]
      if item_name=="" || item_price=="" || item_description==""
        redirect_to edit_item_path(params[:id]) , notice: "Fields Cannot be empty"
      else
        @oldBrand = @item.getbrand
        @item.update(title: item_name, price: item_price , description: item_description)
        unless @av.nil?
          @item.update(avatar: @av)
        end
        @oldBrand.items.delete(@item) unless @oldBrand.nil?
        @updateItem = Item.find_by(id: params[:id])
        @newBrand.items << @updateItem
        redirect_to root_path
      end
    else
      redirect_to edit_item_path(params[:id]) , notice: "Category/Subcategory/Brand Cannot be empty"
    end
  end

  def destroy
    itemToDelete = Item.find_by(id: params[:id])
    itemToDelete.destroy
    redirect_to root_path
  end
  private
  	def set_post
  		@my_item = Item.find(params[:id]) 
  	end 


end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_list.html.erb
<div class="update-body">
	<% @all_items.each do |item| %>
	<section class="col-sm-4 col-md-3">
		<div class="card" style="width: 20rem;">
  		<%= image_tag item.avatar.url(:thumb) %>
  		<div class="card-body">
    		<h4 class="card-title"><%= item.title %></h4>
    		<p class="card-text">The price is : <%= item.price %> </p>
    		<%= link_to "View" , item , class: "btn btn-success" %>
    		<%= link_to "Destroy" , item , method: "delete" , data:  {confirm: 'Are you sure?'} , class: "btn btn-danger" if is_admin? %>
    		<%= link_to "Edit" , edit_item_path(item), method: "get" , class: "btn btn-primary" if is_admin? %>
  		</div>
		</div>
	</section>
	<% end %>
</div>

app/views/items/edit.html.erb
<%= notice %>
<h3> Edit Item </h3>
<%= form_for(@my_item) do |f| %>

<div class="form-group row">
	<%= f.label :title , class: "col-sm-1 col-sm-label" %>
	<div class="col-sm-6">
		<%= f.text_field :title , class: "form-control" %>
	</div>
</div>
<div class="form-group row">
	<%= f.label :price , class: "col-sm-1 col-sm-label" %>
	<div class="col-sm-6">
		<%= f.text_field :price , class: "form-control" %>
	</div>
</div>
<div class="form-group row" >
	<%= f.label :description , class: "col-sm-1 col-sm-label" %>
	<div class="col-sm-6">
		<%= f.text_area :description , class: "form-control" %>
	</div>
</div>
	<%= f.label :avatar %>
	<%= f.file_field :avatar %>
<br>
<div class=field>
	<%= f.label :category %>
	<%= select_tag(:category , options_from_collection_for_select( Category.all , :id , :name, @my_item.getcategory.nil? ? "" : @my_item.getcategory[:id] ) , { class: "auto-update"} ) %>
</div>
<div class=field>
		<%= f.label :subcategory %>
	<%= select_tag(:subcategory , options_from_collection_for_select(  @my_item.getsubcategory.nil? ? [] : @my_item.getcategory.subcategories.all , :id , :name, @my_item.getsubcategory.nil? ? "" : @my_item.getsubcategory[:id] ) , { class: "sub-update"} ) %>
</div>
<div class=field>
	<%= f.label :brand %>
	<%= select_tag(:brand , options_from_collection_for_select( @my_item.getbrand.nil? ? [] :  @my_item.getsubcategory.brands.all , :id , :name, @my_item.getbrand.nil? ? "" : @my_item.getbrand[:id] ) , { class: "brand"} ) %>
</div>
<br>
<%= f.submit class: "btn btn-success" %>
<% end %>

app/views/items/index.html.erb
<div class="row">
	<div class="col-sm-3 sidebar">
		<%= form_tag items_path , { method: "get", remote: true, id: "buga"} do %>
		<p>Category:</p>
		<p><%= select_tag( :category , options_from_collection_for_select( Category.all , :id , :name , @cat.nil? ? "" : @cat.id) , { prompt: "Select Category" , onchange: "$('#buga').submit()"} ) %></p>
		<p>Sub-Category: </p>
		<p class="updated"><%= select_tag(:subcategory , options_from_collection_for_select([] , :id , :name), {prompt: "Select Subcategory" , onchange: "$('#buga').submit()"}) %></p>
		<p>Brand: </p>
		<p class="updated2"> <%= select_tag(:brand , options_from_collection_for_select([], :id , :name), {prompt: "Select brand"}) %>  </p>
		<% end %>

		<ul class="nav nav-pills nav-stacked">
			<% if logged_in?  %> 
			<li> <%= link_to "My Account" , current_user , class: "nav-link" %> </li>
			<li> <%= link_to "My cart" , carts_path , class: "nav-link" %> </li>
			<li> <%= link_to "Admin Dashboard" , admin_index_path, method: "get" , class: "nav-link" if is_admin? %></li>
			<% end %>

		</ul>
	</div>
	<div class="updated3 col-sm-offset-3">
		<h5><%= alert %> </h5>
		<%= render 'list' %>
	</div>
</div>

app/views/items/index.js.erb
$(".updated").html('<%= j select_tag(:subcategory,options_from_collection_for_select( @cat.subcategories.all , :id , :name , @subcat.nil? ? "" : @subcat.id) , {prompt: "Select Subcategory" , onchange: "$(\'#buga\').submit()"}) %>');


<% if @subcat.nil? %>
	$(".updated2").html('<%= j select_tag(:brand,options_from_collection_for_select( [] , :id , :name , @cat.nil? ? "" : @cat.id) , {prompt: "Select Brand" , onchange: "$(\'#buga\').submit()" }) %>');	
<% end %>

<% unless @subcat.nil?  %>
	$(".updated2").html('<%= j select_tag(:brand,options_from_collection_for_select( @subcat.brands.all , :id , :name , @brand.nil? ? "" : @brand.id) , {prompt: "Select Brand" , onchange: "$(\'#buga\').submit()"}) %>');	
<% end %>

$(".updated3").html("<%= j render 'list' %>");

app/views/items/new.html.erb
<h4><%= notice %> </h4>
<h4><%= alert %> </h4>
<h4> <%= link_to "Admin Dashboard" , admin_index_path , method: "get" , class: "btn btn-success" %>
<h3>Add new Item </h3>
<%= form_tag items_path , { method: "post", id: "buga" , multipart: true }  do %>
	<div class="field form-group row">
		<%= label_tag :title , nil ,class: "col-sm-2 col-form-label"  %>
		<div class="col-sm-6">
			<%= text_field_tag :title , nil ,class: "form-control" %>
		</div>
	</div> 
		<div class="field form-group row">
		<%= label_tag :price , nil , class: "col-sm-2 col-form-label" %>
		<div class="col-sm-6">
			<%= text_field_tag :price, nil , class: "form-control" %>
		</div>
	</div> 
	<div class="field form-group row">
		<%= label_tag :description , nil , class: "col-sm-2 col-form-label" %>
		<div class="col-sm-6">
			<%= text_area_tag :description , nil , class: "form-control" %>
		</div>
	</div> 

	<div class="field form-group row" >
		<%= file_field_tag :avatar , class: "col-sm-6" %>
	</div>
	<div class=field>
		<%= select_tag(:category , options_from_collection_for_select( Category.all , :id , :name) , { prompt: "Select Category" , class: "auto-update"} ) %>
	</div>
	<div class=field>
		<%= select_tag(:subcategory , "" , {prompt: "Select subcategory", class: "sub-update"} ) %>
	</div>
	<div class=field>
		<%= select_tag(:brand , "" , {prompt: "Select Brand", class: "brand"} ) %>
	</div>
	<div class="action form-group row">
		<div class="col-sm-6">
			<%= submit_tag("Create Item", class: "btn btn-primary") %>
		</div>
	</div>
<% end %>
<br>
<br>

app/views/items/show.html.erb
<div class="row">
	<h2>Welcome to Details Page </h2>
	<section>
		<h3 class="text-center">
			<%= @my_item.title %>
		</h3>
		<%= image_tag @my_item.avatar.url(:medium) , class: "pull-left col-sm-3"  %>
		<p class= "col-sm-offset-4">Price : <%= @my_item.price %></p> 
		<p class= "col-sm-offset-4">Description: <%= @my_item.description %></p>
		<p class= "col-sm-offset-4"><%= link_to "Add to Cart" , carts_path(@my_item) , method: :post %></p>
	</section>
</div>