config/routes.rb
Rails.application.routes.draw do

  resources :brands , only: [:index , :edit, :update ,:new ,:create , :destroy]
  resources :subcategories, only: [:new ,:index,:edit,:update,:create , :destroy]
  resources :admin , only: [:index , :edit ,:update]
  resources :categories , only: [:new,:create,:edit,:update,:destroy]
  resources :users
  resources :items
  resources :carts
  root 'items#index'

  resources :sessions , only: [:new , :create , :destroy]
  get "/login" => "sessions#new" , as: "login"
  delete "/logout" => "sessions#destroy" , as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name , presence: true , uniqueness: {case_sensitive: false}
	has_many :subcategories , dependent: :destroy
	has_many :items , through: :subcategories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
    @newCat = Category.new
    @allCat = Category.all
  end

  def create
  	@createCat = Category.new(category_params)
  	if @createCat.save
  		redirect_to new_category_path , notice: "Successfully added category"
  	else
  		redirect_to new_category_path , notice: "Category Already exists/Blank Field"
  	end 
  end

  def edit
    @cat = Category.find_by(id: params[:id])
  end

  def update 
    newCat = params[:category][:name]
    catId = params[:id]
    cat = Category.find_by(id: catId)
    cat.update name: newCat
    redirect_to new_category_path
  end

  def destroy
  	@delCat = Category.find_by(id: params[:id])
  	@delCat.destroy
  	redirect_to new_category_path
  end

  private
  	def category_params
  		params.require(:category).permit(:name)
  	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h4> <%= link_to "Back" , new_category_path , method: "get" , class: "btn btn-success" %> </h4>
<h4> Edit Category </h4>
<%= form_for(@cat) do |t| %>
<div class="field from-group row">
	<%= t.label :name , class: "col-sm-2 col-sm-label" %>
	<div class="col-sm-6">
		<%= t.text_field :name , class: "form-control" %>
	</div>
</div>
<%= t.submit "Update" , class: "btn btn-success" %>
<% end %>

app/views/categories/new.html.erb
<h5><%= notice %></h5>
<h4> <%= link_to "Admin Dashboard" , admin_index_path , method: "get" , class: "btn btn-success" %>
<h3>1. Add new category </h3>
<%= form_for(@newCat) do |f| %>
	<div class= "field" >
		<%= f.label :name %>
		<%= f.text_field :name %>
		<%= f.submit :Create , class: "btn btn-success" %>
	</div>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>Category Name</th>
      <th>Options</th>
    </tr>
  </thead>
  <tbody>
  	<% @allCat.each do |cat| %>
    <tr>
      <td scope="row"><%= cat[:name] %></td>
      <td> <%=link_to "Edit" , edit_category_path(cat.id) %> / <%= link_to "Destroy" , cat , method: :delete%></td>
    </tr>
  <% end %>
  </tbody>
</table>